### ISSUE TITLE
How to return 201 Created for PUT method

### ISSUE THREAD

**Issue by kgish** [seancribbs/webmachine-ruby#209]
For a `PUT` request that passes an `ID` of a non-existent resource, I would like to create a new resource with that `ID` and pass back `201 Created` according to the HTTP specs.

However, when I try the following it doesn't work. Any ideas what I am doing wrong?

```ruby
  def from_json
    if request.method === 'PUT'
      if @resource
        delete_resource
        response.code = 201 # <= does not work
      end
      attributes = params
      attributes['id'] = id
      new_product = Product.from_attributes(attributes)
      $products << new_product
      response.body = new_product.to_json
    else
      $products << @resource.from_json(request.body.to_s, :except => [:id])
    end
  end
```

**Comment by Asmod4n** [comment]
afaik you have to set a location header aka response.headers['Location'] =
If you want to set the response code yourself it must be the return value of a callback.

But its easier to just use POST and use create_path: https://github.com/seancribbs/webmachine-ruby/blob/master/documentation/examples.md#post-to-create-a-new-resource-in-a-collection

**Comment by seancribbs** [comment]
The thing is, if the resource *did not* exist, Webmachine should be returning 201 for you, without you setting anything. This could be a bug.

**Comment by bethesque** [comment]
It doesn't, I've always had to do this manually. https://github.com/bethesque/pact_broker/blob/master/lib/pact_broker/api/resources/pact.rb#L45

**Comment by bethesque** [comment]
@kgish, you need to return the response code, not set it, see the link in my previous comment.

**Comment by bethesque** [comment]
BTW, Webmachine is designed so you can do almost everything without having to do any `if request.xxx == yyy`, because each callback should have one and only one concern, and by the time you reach a certain callback, you should already have the knowledge you require by the simple fact of having reached that callback (eg. if you mapped `application/json` to `to_json` in `content_types_provided`,  and you're in the `to_json` method, then you already know that `request.method` == 'GET'). If you find yourself doing `if request.xxx == yyy` type code, it's a hint that there's probably another more Webmachiney way to do what you're trying to achieve.

For example, a POST to create an item in a collection belongs in a collection resource, and would be handled by a `from_json` method there. A PUT to update a resource belongs in the item's resource, and would be handled by a `from_json` method there. In each resource, `from_json` has only one responsibility, so there's no need to do an `if request...` check.

**Comment by kgish** [comment]
@bethesque, that works for me thanks.
